--BANKING APPLICATION:

--Create tables:
CREATE TABLE CUSTOMER(CID SMALLINT, CNAME VARCHAR(50),PRIMARY KEY(CID));
CREATE TABLE BRANCH(BCODE SMALLINT, BNAME VARCHAR(50),PRIMARY KEY(BCODE));
CREATE TABLE ACCOUNT(ANO BIGINT, ATYPE CHAR CHECK(ATYPE IN ('S','C')), BALANCE FLOAT(10), CID SMALLINT, BCODE SMALLINT, PRIMARY KEY(ANO), FOREIGN KEY (CID) REFERENCES CUSTOMER (CID), FOREIGN KEY (BCODE) REFERENCES BRANCH (BCODE));
